import type { FilterKey } from "./video-page-types";
import type { ProductionPackage } from "./use-video-package-store";

export const initialPackages: ProductionPackage[] = [
    {
        projectId: "demo-project",
        episodeId: "demo-episode",
        sceneKey: "scene-01",
        order: 1,
        id: "P01",
        segment: "雨夜天桥，女主发现遗落的加密芯片",
        duration: "8s",
        promptStatus: "已确认",
        assetStatus: "完整",
        canvasStatus: "已导入",
        prompt: "雨夜霓虹天桥，女主低头捡起一枚微弱发光的加密芯片，镜头从湿漉漉的地面低角度推近到她警觉的侧脸，远处警灯反射在玻璃幕墙上，节奏克制、悬疑。",
        tags: { 运镜: "低角度推近，结尾轻微上摇", 主体动作: "拾起芯片后迅速环顾四周", 环境: "雨夜天桥、霓虹反射、远处警灯", 光影: "青蓝主光，红色警灯扫过", 节奏: "前慢后紧，8 秒内完成发现动作" },
        assets: [
            { kind: "角色图", name: "林夏·雨衣造型", status: "已绑定" },
            { kind: "场景图", name: "天桥夜景", status: "已绑定" },
            { kind: "道具图", name: "加密芯片", status: "已绑定" },
            { kind: "上一镜尾帧", name: "P00 尾帧", status: "已绑定" },
        ],
        config: { model: "Seedance 2.0 Pro", ratio: "16:9", duration: "8s", resolution: "1080p", motion: "中", frames: "使用首尾帧" },
        risks: [{ level: "提示", text: "镜头动作清晰，可直接进入画布生成节点。" }],
    },
    {
        projectId: "demo-project",
        episodeId: "demo-episode",
        sceneKey: "scene-02",
        order: 2,
        id: "P02",
        segment: "地下停车场，追踪者从柱后现身",
        duration: "12s",
        promptStatus: "待审核",
        assetStatus: "缺角色图",
        canvasStatus: "未导入",
        prompt: "地下停车场冷白灯闪烁，追踪者从水泥柱后缓慢现身，主角背对镜头察觉异常后停步，镜头横移穿过车辆缝隙，制造被窥视感，最后定格在追踪者手中的旧式通讯器。",
        tags: { 运镜: "横移穿车缝，末尾定格", 主体动作: "追踪者现身，主角停步回头", 环境: "地下停车场、车辆阴影、水泥柱", 光影: "冷白灯闪烁，局部暗区", 节奏: "中速推进，末尾悬停" },
        assets: [
            { kind: "角色图", name: "追踪者制服设定", status: "缺失" },
            { kind: "场景图", name: "地下停车场", status: "已绑定" },
            { kind: "道具图", name: "旧式通讯器", status: "已绑定" },
            { kind: "上一镜尾帧", name: "P01 尾帧", status: "已绑定" },
        ],
        config: { model: "Seedance 2.0 Pro", ratio: "16:9", duration: "12s", resolution: "1080p", motion: "中高", frames: "使用首尾帧" },
        risks: [
            { level: "注意", text: "缺少追踪者角色图，导入画布前建议绑定角色参考。" },
            { level: "提示", text: "12 秒内动作数量可控，但末尾定格需避免与下一包衔接断裂。" },
        ],
    },
    {
        projectId: "demo-project",
        episodeId: "demo-episode",
        sceneKey: "scene-03",
        order: 3,
        id: "P03",
        segment: "监控室，屏幕显示关键证据被远程删除",
        duration: "15s",
        promptStatus: "需修改",
        assetStatus: "缺场景图",
        canvasStatus: "未导入",
        prompt: "监控室内多块屏幕同时闪烁，技术员快速切换窗口试图恢复证据，主角冲进画面质问，屏幕上的文件夹逐个变红并消失，镜头环绕两人和屏幕形成紧张压迫。",
        tags: { 运镜: "半环绕加快速切屏", 主体动作: "技术员操作、主角冲入、文件消失", 环境: "监控室、多屏幕、数据面板", 光影: "屏幕蓝绿光为主，红色警示闪烁", 节奏: "信息量偏高，需压缩动作" },
        assets: [
            { kind: "角色图", name: "技术员", status: "已绑定" },
            { kind: "场景图", name: "监控室", status: "缺失" },
            { kind: "道具图", name: "证据文件 UI", status: "已绑定" },
            { kind: "上一镜尾帧", name: "P02 尾帧", status: "缺失" },
        ],
        config: { model: "Seedance 2.0 Pro", ratio: "16:9", duration: "15s", resolution: "1080p", motion: "高", frames: "仅首帧" },
        risks: [
            { level: "阻断", text: "动作过多且 15 秒达到上限，建议拆成技术员恢复证据和主角冲入两个生产包。" },
            { level: "注意", text: "缺少监控室场景图和上一镜尾帧，镜头衔接不明确。" },
        ],
    },
    {
        projectId: "demo-project",
        episodeId: "demo-episode",
        sceneKey: "scene-04",
        order: 4,
        id: "P04",
        segment: "街边便利店外，线人交出备份密钥",
        duration: "8s",
        promptStatus: "待审核",
        assetStatus: "完整",
        canvasStatus: "未导入",
        prompt: "便利店招牌的红绿灯光照在雨棚下，线人把备份密钥塞进主角掌心后迅速离开，镜头跟随手部特写再切到主角抬眼，背景车流形成拖影。",
        tags: { 运镜: "手部特写跟随，轻切抬眼", 主体动作: "线人交付密钥后离开", 环境: "便利店雨棚、街边车流", 光影: "红绿招牌光与湿地反射", 节奏: "短促直接，留出情绪停顿" },
        assets: [
            { kind: "角色图", name: "线人", status: "已绑定" },
            { kind: "场景图", name: "便利店街边", status: "已绑定" },
            { kind: "道具图", name: "备份密钥", status: "已绑定" },
            { kind: "上一镜尾帧", name: "P03 尾帧", status: "已绑定" },
        ],
        config: { model: "Seedance 2.0 Lite", ratio: "16:9", duration: "8s", resolution: "720p", motion: "中", frames: "使用首尾帧" },
        risks: [{ level: "提示", text: "提示词聚焦单一动作，适合确认后导入画布。" }],
    },
    {
        projectId: "demo-project",
        episodeId: "demo-episode",
        sceneKey: "scene-05",
        order: 5,
        id: "P05",
        segment: "楼顶对峙，反派说出真相",
        duration: "12s",
        promptStatus: "已确认",
        assetStatus: "完整",
        canvasStatus: "已生成",
        prompt: "城市楼顶强风中，反派站在霓虹广告牌下说出真相，主角向前一步停住，镜头从两人之间的空隙缓慢推进，远处城市灯海压低，情绪冷峻。",
        tags: { 运镜: "双人间隙慢推", 主体动作: "反派陈述，主角克制逼近", 环境: "城市楼顶、霓虹广告牌", 光影: "背光轮廓，冷色城市灯海", 节奏: "慢速压迫，适合台词段" },
        assets: [
            { kind: "角色图", name: "反派楼顶造型", status: "已绑定" },
            { kind: "场景图", name: "城市楼顶", status: "已绑定" },
            { kind: "道具图", name: "广告牌", status: "已绑定" },
            { kind: "上一镜尾帧", name: "P04 尾帧", status: "已绑定" },
        ],
        config: { model: "Seedance 2.0 Pro", ratio: "16:9", duration: "12s", resolution: "1080p", motion: "低", frames: "使用首尾帧" },
        risks: [{ level: "提示", text: "已在画布生成视频版本，后续版本选择请到画布完成。" }],
    },
];

export const videoFilters: { key: FilterKey; label: string }[] = [
    { key: "all", label: "全部" },
    { key: "review", label: "待审核" },
    { key: "missing", label: "缺参考" },
    { key: "ready", label: "已确认" },
    { key: "imported", label: "已导入画布" },
    { key: "generated", label: "已生成" },
];
